### ISSUE TITLE
Brutal stops of UR5 robot while planning trajectories

### ISSUE THREAD

**Issue by flamato** [vfdev-5/ur5_pnp#2]
We have observed brutal stops of UR5 robot while planning trajectories.

We are using UR modern driver with ROS kinetic on Ubuntu 16.04 LTS.  

We believe that the problem is related to velocity or acceleration control.
Do we have to add velocity or acceleration constraints on planning ? or 
Do we have to tune some planning parameters ? 

DoD:
* [ ] Code should work with real robot without brutal stops

**Comment by vfdev-5** [comment]
Working on that. Maybe solved with [this](https://github.com/vfdev-5/ur5_pnp/commit/27b0a547d56ee6a909e0bd9b6fcb918c08739144#diff-82505e0bc9a1cc6bdaa216a514d1da6f)

**Comment by himratoko** [comment]
The speed control of the UR5 while planning trajectories in rviz can be overwritten in the moveit joint_limits.yalm file.

**Comment by vfdev-5** [comment]
Fixed with [27b0a54](https://github.com/vfdev-5/ur5_pnp/commit/27b0a547d56ee6a909e0bd9b6fcb918c08739144#diff-82505e0bc9a1cc6bdaa216a514d1da6f)
